Check point 2
VladikBrown/phoneshop pull request #5
Opened 2020-11-04 13:49 UTC by VladikBrown

2020-11-09 15:44 UTC, Alastifer requested changes

2020-11-09 15:44 UTC, Alastifer commented on core/src/main/java/com/es/core/model/DAO/phone/PhoneFieldsConstantsController.java
> +    public String getBRAND_UNIQUE() {
зачем геттеры на публичные филды?

2020-11-09 15:44 UTC, Alastifer commented on core/src/main/java/com/es/core/service/cart/CartService.java
> +public interface CartService<SessionResource>{
Без генерика обойдемся

2020-11-09 15:44 UTC, Alastifer commented on core/src/main/java/com/es/core/service/cart/HttpSessionCartService.java
> +    @Autowired
??? Это как? Ты же через конструктор всё сетаешь

2020-11-09 15:44 UTC, Alastifer commented on core/src/main/java/com/es/core/service/cart/HttpSessionCartService.java
> +                httpSession.setAttribute(CART_SESSION_ATTRIBUTE, cart = new Cart());
давай без такого cart = new Cart()

2020-11-09 15:44 UTC, Alastifer commented on core/src/main/java/com/es/core/service/cart/HttpSessionCartService.java
> +        } else return BigDecimal.ZERO;
форматирование

2020-11-09 15:44 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +    @Qualifier("addPhoneDtoValidator")
зачем он тут?

2020-11-09 15:44 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
>  @RequestMapping(value = "/ajaxCart")
неинформативный урл

2020-11-09 15:44 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
>      @RequestMapping(method = RequestMethod.GET)
getmapping

2020-11-09 15:44 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
>      @RequestMapping(method = RequestMethod.PUT)
putmapping

2020-11-09 15:44 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        cartService.update(null, null);
что за апдейт такой?

2020-11-09 15:44 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
>      @RequestMapping(method = RequestMethod.GET)
гетмаппинг

2020-11-09 15:44 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +    private static final int DEFAULT_RECORDS_LIMIT = 10;
отступ

2020-11-09 15:44 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/validation/AddPhoneDtoValidator.java
> +@Qualifier("addPhoneDtoValidator")
зачем?

2020-11-09 15:44 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/validation/AddPhoneDtoValidator.java
> +            errors.rejectValue("quantity","ONLY_NUMS", "Only digits are allowed");
что за второй параметр?

2020-11-09 15:44 UTC, Alastifer commented on web/src/main/webapp/WEB-INF/dispatcher-servlet.xml
> +    <mvc:default-servlet-handler/>
для чего?

2020-11-09 15:44 UTC, Alastifer commented on web/src/main/webapp/WEB-INF/pages/productList.jsp
> +<jsp:useBean id="phoneFields" class="com.es.core.model.DAO.phone.PhoneFieldsConstantsController" scope="application"/>
зачем?

2020-11-10 07:32 UTC, VladikBrown commented on web/src/main/webapp/WEB-INF/dispatcher-servlet.xml
> +    <mvc:default-servlet-handler/>
mvc:annotation driven для использования аннотаций Spring mvc, а благодаря default-servlet-handler статические ресурсы подгружаются нормально

2020-11-10 07:41 UTC, VladikBrown commented on web/src/main/java/com/es/phoneshop/web/controller/validation/AddPhoneDtoValidator.java
> +@Qualifier("addPhoneDtoValidator")
Очень вероятно, что валидаторов в приложении будет больше, чем один. Можно было бы наверное @Resource использовать, было бы уместнее

2020-11-10 07:46 UTC, VladikBrown commented on web/src/main/webapp/WEB-INF/pages/productList.jsp
> +<jsp:useBean id="phoneFields" class="com.es.core.model.DAO.phone.PhoneFieldsConstantsController" scope="application"/>
Хотелось, чтобы параметры в url не были случайными, а согласовывались с именами, которые в модели используются

2020-11-10 07:52 UTC, VladikBrown commented on core/src/main/java/com/es/core/service/cart/HttpSessionCartService.java
> +                httpSession.setAttribute(CART_SESSION_ATTRIBUTE, cart = new Cart());
Не понял. Инстанцировать отдельно (Cart cart = new Cart() - > foo(arg, cart))?

2020-11-10 07:54 UTC, VladikBrown commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +    @Qualifier("addPhoneDtoValidator")
Аналог @Resource т.к. валидаторов приложении очень вероятно будет больше, чем один

2020-11-10 10:17 UTC, VladikBrown commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
>  @RequestMapping(value = "/ajaxCart")
Придумать что-то лучше, чем /ajaxCart?

2020-11-10 17:45 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
>  @RequestMapping(value = "/ajaxCart")
я уже сказал

2020-11-10 17:46 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/validation/AddPhoneDtoValidator.java
> +@Qualifier("addPhoneDtoValidator")
используй ресурс

2020-11-10 17:47 UTC, Alastifer commented on web/src/main/webapp/WEB-INF/dispatcher-servlet.xml
> +    <mvc:default-servlet-handler/>
про последнюю аннотацию не понял

2020-11-10 17:47 UTC, Alastifer commented on web/src/main/webapp/WEB-INF/pages/productList.jsp
> +<jsp:useBean id="phoneFields" class="com.es.core.model.DAO.phone.PhoneFieldsConstantsController" scope="application"/>
фигня, выноси в енамы тогда

2020-11-10 17:57 UTC, VladikBrown commented on web/src/main/webapp/WEB-INF/dispatcher-servlet.xml
> +    <mvc:default-servlet-handler/>
This tag allows for mapping the DispatcherServlet to "/" (thus overriding the mapping of the container's default Servlet), while still allowing static resource requests to be handled by the container's default Servlet. It configures a DefaultServletHttpRequestHandler with a URL mapping (given a lowest precedence order) of "/**". This handler will forward all requests to the default Servlet.  Аккординг ту спринг докс

2020-11-10 17:59 UTC, VladikBrown commented on web/src/main/java/com/es/phoneshop/web/controller/validation/AddPhoneDtoValidator.java
> +@Qualifier("addPhoneDtoValidator")
Согласен, уже исправлено

2020-11-10 18:03 UTC, Alastifer commented on core/src/main/java/com/es/core/service/cart/HttpSessionCartService.java
> +                httpSession.setAttribute(CART_SESSION_ATTRIBUTE, cart = new Cart());
да

2020-11-11 07:50 UTC, Alastifer approved these changes

2020-11-11 07:51 UTC, merged