Task 2.8 and Task 2.9 Implemented Order page and Order Overview page
VladikBrown/phoneshop pull request #7
Opened 2020-11-24 16:54 UTC by VladikBrown

Check point 4

2020-11-28 12:02 UTC, Alastifer requested changes

2020-11-28 12:02 UTC, Alastifer commented on core/src/main/java/com/es/core/model/DAO/order/JdbcOrderDao.java
> +            "secureId, firstName, lastName, deliveryAddress, contactPhoneNo, additionalInformation, " +
а зачем все филды доставать?

2020-11-28 12:02 UTC, Alastifer commented on core/src/main/java/com/es/core/model/DAO/order/JdbcOrderDao.java
> +    private JdbcTemplate jdbcTemplate;
добавь пустых строк

2020-11-28 12:02 UTC, Alastifer commented on core/src/main/java/com/es/core/model/DAO/order/JdbcOrderDao.java
> +        return Optional.of(resultOrder);
разделяй код на логические блоки с помощью пустых строк

2020-11-28 12:02 UTC, Alastifer commented on core/src/main/java/com/es/core/model/entity/cart/CartItem.java
> +    public Phone getPhone() {
поменяй обратно на продукт. У тебя не только телефон может быть

2020-11-28 12:02 UTC, Alastifer commented on core/src/main/java/com/es/core/model/entity/order/Order.java
> +     * A sum of order item prices;
убери коммент

2020-11-28 12:02 UTC, Alastifer commented on core/src/main/test/com/es/core/model/entity/phone/jdbcPhoneDao/JdbcPhoneDaoIntTestConfiguration.java
> +        //jdbcPhoneDao.setDataSource(testDataSource);
удали

2020-11-28 12:02 UTC, Alastifer commented on web/src/main/java/com/es/phoneshop/web/controller/pages/OrderPageController.java
> +    private CartService cartService;
почему ресурсы и автоваер в одном месте?

2020-11-30 15:51 UTC, VladikBrown commented on core/src/main/java/com/es/core/model/DAO/order/JdbcOrderDao.java
> +            "secureId, firstName, lastName, deliveryAddress, contactPhoneNo, additionalInformation, " +
А какие лишнее? вся информация связанная с Order вроде нужна, как и Phone, которые в Order содержаться

2020-11-30 16:09 UTC, Alastifer commented on core/src/main/java/com/es/core/model/DAO/order/JdbcOrderDao.java
> +            "secureId, firstName, lastName, deliveryAddress, contactPhoneNo, additionalInformation, " +
ты их все юзаешь?

2020-11-30 16:15 UTC, VladikBrown commented on core/src/main/java/com/es/core/model/DAO/order/JdbcOrderDao.java
> +            "secureId, firstName, lastName, deliveryAddress, contactPhoneNo, additionalInformation, " +
Нужно только те, которые непосредственно в таблице отображаются? Как то странно....

2020-12-01 04:10 UTC, Alastifer approved these changes

2020-12-01 04:10 UTC, merged